package com.example.EmployeeMuthia.models;
// Generated Nov 11, 2020 9:27:58 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tingkatan generated by hbm2java
 */
@Entity
@Table(name = "tingkatan", schema = "public")
public class Tingkatan implements java.io.Serializable {

	private long idTingkatan;
	private String namaTingkatan;
	private Set<Karyawan> karyawans = new HashSet<Karyawan>(0);
	private Set<TunjanganPegawai> tunjanganPegawais = new HashSet<TunjanganPegawai>(0);

	public Tingkatan() {
	}

	public Tingkatan(long idTingkatan, String namaTingkatan) {
		this.idTingkatan = idTingkatan;
		this.namaTingkatan = namaTingkatan;
	}

	public Tingkatan(long idTingkatan, String namaTingkatan, Set<Karyawan> karyawans,
			Set<TunjanganPegawai> tunjanganPegawais) {
		this.idTingkatan = idTingkatan;
		this.namaTingkatan = namaTingkatan;
		this.karyawans = karyawans;
		this.tunjanganPegawais = tunjanganPegawais;
	}

	@Id

	@Column(name = "id_tingkatan", unique = true, nullable = false)
	public long getIdTingkatan() {
		return this.idTingkatan;
	}

	public void setIdTingkatan(long idTingkatan) {
		this.idTingkatan = idTingkatan;
	}

	@Column(name = "nama_tingkatan", nullable = false, length = 128)
	public String getNamaTingkatan() {
		return this.namaTingkatan;
	}

	public void setNamaTingkatan(String namaTingkatan) {
		this.namaTingkatan = namaTingkatan;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tingkatan")
	public Set<Karyawan> getKaryawans() {
		return this.karyawans;
	}

	public void setKaryawans(Set<Karyawan> karyawans) {
		this.karyawans = karyawans;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tingkatan")
	public Set<TunjanganPegawai> getTunjanganPegawais() {
		return this.tunjanganPegawais;
	}

	public void setTunjanganPegawais(Set<TunjanganPegawai> tunjanganPegawais) {
		this.tunjanganPegawais = tunjanganPegawais;
	}

}
