package com.example.EmployeeMuthia.models;
// Generated Nov 11, 2020 9:27:58 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TunjanganPegawai generated by hbm2java
 */
@Entity
@Table(name = "tunjangan_pegawai", schema = "public")
public class TunjanganPegawai implements java.io.Serializable {

	private long idTunjanganPegawai;
	private Posisi posisi;
	private Tingkatan tingkatan;
	private BigDecimal besaranTujnaganPegawai;

	public TunjanganPegawai() {
	}

	public TunjanganPegawai(long idTunjanganPegawai, BigDecimal besaranTujnaganPegawai) {
		this.idTunjanganPegawai = idTunjanganPegawai;
		this.besaranTujnaganPegawai = besaranTujnaganPegawai;
	}

	public TunjanganPegawai(long idTunjanganPegawai, Posisi posisi, Tingkatan tingkatan,
			BigDecimal besaranTujnaganPegawai) {
		this.idTunjanganPegawai = idTunjanganPegawai;
		this.posisi = posisi;
		this.tingkatan = tingkatan;
		this.besaranTujnaganPegawai = besaranTujnaganPegawai;
	}

	@Id

	@Column(name = "id_tunjangan_pegawai", unique = true, nullable = false)
	public long getIdTunjanganPegawai() {
		return this.idTunjanganPegawai;
	}

	public void setIdTunjanganPegawai(long idTunjanganPegawai) {
		this.idTunjanganPegawai = idTunjanganPegawai;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_posisi")
	public Posisi getPosisi() {
		return this.posisi;
	}

	public void setPosisi(Posisi posisi) {
		this.posisi = posisi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tingkatan")
	public Tingkatan getTingkatan() {
		return this.tingkatan;
	}

	public void setTingkatan(Tingkatan tingkatan) {
		this.tingkatan = tingkatan;
	}

	@Column(name = "besaran_tujnagan_pegawai", nullable = false, precision = 16, scale = 4)
	public BigDecimal getBesaranTujnaganPegawai() {
		return this.besaranTujnaganPegawai;
	}

	public void setBesaranTujnaganPegawai(BigDecimal besaranTujnaganPegawai) {
		this.besaranTujnaganPegawai = besaranTujnaganPegawai;
	}

}
